[package]
name = "through-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["full"] }
napi-derive = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["signal"] }
